eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10004
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-one/**
      serviceId: service-one
    api-b:
      path: /api-two/**
      serviceId: service-two

