eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10003
spring:
  application:
    name: service-ribbon-feign
feign:
  hystrix:
    enabled: true

spring.cloud.config.label: master
spring.cloud.config.profile: dev
spring.cloud.config.uri:  http://localhost:10005/
myww: myww version 2